services:
  - name: portfolio-backend
    type: web
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false

  - name: portfolio-frontend
    type: web
    runtime: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
